server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie
management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

